// <auto-generated />
namespace QLSV.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_tbla : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_tbla));
        
        string IMigrationMetadata.Id
        {
            get { return "202111081341183_create_tbl a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
