// <auto-generated />
namespace QLSV.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adoluommim : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adoluommim));
        
        string IMigrationMetadata.Id
        {
            get { return "202111210435500_ad-oluommim"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
